### ISSUE TITLE
Add wheel chair detector to tracker

### ISSUE THREAD

**Issue by cdondrup** [strands-project/strands_perception_people#209]
Needs to go here: https://github.com/strands-project/strands_perception_people/blob/indigo-devel/bayes_people_tracker/config/detectors.yaml

Needs to publish a pose array or use to_pose_array

**Comment by Pandoro** [comment]
Am I not getting something, or is it there already?

**Comment by cdondrup** [comment]
Oh, It is... didn't see, sorry :( We had that at the demo as well right?

Then it needs to be added to one of the launch files I guess. Preferably this: https://github.com/strands-project/strands_perception_people/blob/indigo-devel/perception_people_launch/launch/people_tracker_robot.launch

**Comment by Pandoro** [comment]
- [ ] Add a machine parameter for the wheelchair detector (no default should be left side machine on werner)
- [ ] Add a flag with_wheelchairs (default=false)
- [ ] Change the tmux for the aaf bringup accordingly.

Edit: To avoid confusion I decided to not make another "with_laser_filter" parameter separately for the wheelchair detector.
Edit2: Also I set the with_wheelchair to false by default. We cannot provide a proper default for the wheelchair detector machine and this would make it harder to start stuff if cuda etc was not setup correctly.
